# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantlocation_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='catagory',
            new_name='category',
        ),
    ]
