# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantlocation_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
