# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180222_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='my_date_field',
            new_name='timestamp',
        ),
    ]
